using System.ComponentModel;
using Microsoft.Extensions.Logging;

namespace EcommerceSupport.Infrastructure.Tools;

/// <summary>
/// Technical support tools (product troubleshooting, FAQ, device compatibility).
/// Kind of a product knowledge base and first-level diagnositc for common issues.
/// Generated by ChatGPT
/// </summary>

public sealed class TechnicalTools(ILogger<TechnicalTools> logger)
{
    private static readonly Dictionary<string, string> ProductTroubleshooting = new(StringComparer.OrdinalIgnoreCase)
    {
        ["wireless headphones"] =
            "Common fixes:\n" +
            "1. Ensure the headphones are charged (hold power button 3s to check battery level).\n" +
            "2. Clear paired devices: hold power + volume-down for 5s until LED flashes red-blue.\n" +
            "3. Re-pair from scratch via your device's Bluetooth settings.\n" +
            "4. Update firmware via the companion app.\n" +
            "5. If no sound: check the audio output device in your OS settings.",

        ["smart watch"] =
            "Common fixes:\n" +
            "1. Force restart: hold side button + bottom button for 10s.\n" +
            "2. Check Bluetooth connection to the companion app.\n" +
            "3. Ensure watch OS is up to date (Settings > System > Update).\n" +
            "4. Battery drain: disable Always-On Display in Settings > Display.",

        ["mechanical keyboard"] =
            "Common fixes:\n" +
            "1. Check USB cable connection or wireless dongle is plugged in.\n" +
            "2. Test on another USB port or computer.\n" +
            "3. On Windows: Device Manager > Keyboards — check for error flags.\n" +
            "4. Reset to factory defaults: hold Fn + Escape for 3s.",

        ["4k monitor"] =
            "Common fixes:\n" +
            "1. Ensure HDMI 2.0 or DisplayPort 1.4 cable is used for 4K@60Hz.\n" +
            "2. Check display settings: right-click desktop > Display Settings > Resolution.\n" +
            "3. Update GPU drivers.\n" +
            "4. If flickering: try a different cable.",
    };

    [Description("Get troubleshooting steps for a specific product. " +
                 "Use this when the customer reports a technical issue with a product they purchased.")]
    public Task<string> GetTroubleshootingStepsAsync(
        [Description("Product name or type, e.g. 'wireless headphones', 'smart watch'")] string productType)
    {
        logger.LogInformation("GetTroubleshootingSteps for {ProductType}", productType);

        var key = ProductTroubleshooting.Keys.FirstOrDefault(k =>
            productType.Contains(k, StringComparison.OrdinalIgnoreCase));

        if (key is null)
            return Task.FromResult(
                $"I don't have specific troubleshooting steps for '{productType}' yet. " +
                $"General tips:\n" +
                $"1. Power cycle the device.\n" +
                $"2. Check all cable connections.\n" +
                $"3. Check for firmware/software updates.\n" +
                $"4. Try on a different device/port to isolate the issue.\n" +
                $"If the issue persists, I can escalate to a specialized technician.");

        return Task.FromResult($"Troubleshooting steps for {key}:\n{ProductTroubleshooting[key]}");
    }

    [Description("Check product compatibility with a specific device or operating system.")]
    public Task<string> CheckCompatibilityAsync(
        [Description("Product name")] string productName,
        [Description("Device or OS to check compatibility with, e.g. 'iPhone 16', 'Windows 11'")] string deviceOrOs)
    {
        logger.LogInformation("CheckCompatibility: {Product} with {Device}", productName, deviceOrOs);

        // Simplified compatibility matrix — would be a real DB in production
        if (productName.Contains("headphones", StringComparison.OrdinalIgnoreCase))
        {
            return Task.FromResult(
                $"The wireless headphones are compatible with:\n" +
                $"  ✅ iOS 14+ / iPhone 8 and later\n" +
                $"  ✅ Android 8.0+\n" +
                $"  ✅ Windows 10/11 (via Bluetooth)\n" +
                $"  ✅ macOS 11+\n" +
                $"  ❌ Older Bluetooth 3.0 devices (requires Bluetooth 5.0+)");
        }

        return Task.FromResult(
            $"Compatibility for '{productName}' with '{deviceOrOs}': " +
            $"Please refer to the product manual included in your package or visit " +
            $"our support site at https://support.example.com/compatibility for full details.");
    }

    [Description("Create a technical support escalation ticket to a Level 2 technician " +
                 "when basic troubleshooting has not resolved the issue.")]
    public Task<string> EscalateToTechnicianAsync(
        [Description("Customer's description of the unresolved issue")] string issueDescription,
        [Description("Steps already tried by the customer")] string stepsTried)
    {
        logger.LogInformation("EscalateTechnician: {Issue}", issueDescription);

        var caseId = $"TECH-{Guid.NewGuid().ToString("N")[..6].ToUpper()}";

        return Task.FromResult(
            $"✅ Escalation ticket created.\n" +
            $"  Case ID: {caseId}\n" +
            $"  A Level 2 technician will contact you within 4 business hours via email.\n" +
            $"  Issue recorded: {issueDescription}\n" +
            $"  Steps already tried: {stepsTried}");
    }
}
